# ruff: noqa: F405 -- __all__ lists ufunc/gufunc names that arrive via star imports
from importlib.metadata import PackageNotFoundError as _PackageNotFoundError
from importlib.metadata import version as _dist_version

import dask as _dask
import numpy as _np

# Rechunk's threshold trades data copies for tasks: a higher value means fewer
# intermediate copies and more tasks. Frisky makes tasks cheap, so we raise the
# planner's default from dask's 4 to 32 (benchmarks: single-copy rechunks win
# 15-35%). update_defaults respects an explicit user setting (but a
# dask.config.refresh() would revert it to 4). The separate p2p-vs-tasks choice
# stays at 4 (see _choose_rechunk_method).
# unify-chunks-policy picks the common layout when elemwise operands disagree
# on chunking: "auto" (default) merges nested chunkings up to the coarsest
# operand unless the merge would move more bytes than the operands backing
# that layout justify (then it refines instead -- splits only, no data moves);
# "coarse" always merges; "refine" opts into stock-dask refinement.
# unify-chunks-limit caps how large a chunk a merge may manufacture under any
# policy (above it, unification refines and warns).
_dask.config.update_defaults(
    {
        "array": {
            "rechunk": {"threshold": 32},
            "unify-chunks-limit": "512 MiB",
            "unify-chunks-policy": "auto",
        }
    }
)

from dask_array import _backends as _backends
from dask_array import chunk
from dask_array._core_utils import PerformanceWarning, normalize_chunks
from dask_array._diagnostics import chunk_report, explain, trace_rewrites
from dask.base import compute
from dask_array._chunk_types import register_chunk_type

from dask_array import fft, random
from dask_array._collection import (
    Array,
    array,
    asanyarray,
    asarray,
    atleast_1d,
    atleast_2d,
    atleast_3d,
    block,
    blockwise,
    broadcast_to,
    concatenate,
    dstack,
    elemwise,
    expand_dims,
    flip,
    fliplr,
    flipud,
    from_array,
    hstack,
    moveaxis,
    ravel,
    rechunk,
    reshape,
    reshape_blockwise,
    roll,
    rollaxis,
    rot90,
    squeeze,
    stack,
    swapaxes,
    transpose,
    vstack,
)
from dask_array._einsum import einsum
from dask_array._gufunc import *
from dask_array._histogram import histogram, histogram2d, histogramdd
from dask_array._map_blocks import map_blocks
from dask_array._overlap import map_overlap, overlap, push, sliding_window_view, trim_overlap
from dask_array.routines import (
    aligned_coarsen_chunks,
    allclose,
    append,
    apply_along_axis,
    apply_over_axes,
    argtopk,
    argwhere,
    around,
    average,
    bincount,
    broadcast_arrays,
    choose,
    coarsen,
    compress,
    corrcoef,
    count_nonzero,
    cov,
    delete,
    diff,
    digitize,
    ediff1d,
    extract,
    flatnonzero,
    gradient,
    insert,
    isclose,
    iscomplexobj,
    isin,
    isnull,
    ndim,
    nonzero,
    notnull,
    outer,
    piecewise,
    ptp,
    ravel_multi_index,
    result_type,
    round,
    searchsorted,
    select,
    shape,
    take,
    topk,
    tril,
    tril_indices,
    tril_indices_from,
    triu,
    triu_indices,
    triu_indices_from,
    unify_chunks,
    union1d,
    unique,
    unravel_index,
    where,
)
from dask_array._shuffle import shuffle
from dask_array._ufunc import *
from dask_array.creation import (
    arange,
    diag,
    diagonal,
    empty,
    empty_like,
    eye,
    fromfunction,
    full,
    full_like,
    indices,
    linspace,
    meshgrid,
    ones,
    ones_like,
    pad,
    repeat,
    tile,
    tri,
    zeros,
    zeros_like,
)
from dask_array.io import (
    from_delayed,
    from_map,
    from_npy_stack,
    from_tiledb,
    from_zarr,
    store,
    to_hdf5,
    to_npy_stack,
    to_tiledb,
    to_zarr,
)
from dask_array.linalg import dot, matmul, tensordot, vdot
from dask_array.reductions import (
    _tree_reduce,
    all,
    any,
    arg_reduction,
    argmax,
    argmin,
    cumprod,
    cumreduction,
    cumsum,
    max,
    mean,
    median,
    min,
    moment,
    nanargmax,
    nanargmin,
    nancumprod,
    nancumsum,
    nanmax,
    nanmean,
    nanmedian,
    nanmin,
    nanpercentile,
    nanprod,
    nanquantile,
    nanstd,
    nansum,
    nanvar,
    percentile,
    prod,
    quantile,
    reduction,
    std,
    sum,
    trace,
    var,
)
from dask_array._expr_flow import expr_flow
from dask_array._visualize import expr_table
from dask_array import xarray

try:
    __version__ = _dist_version("dask-array")
except _PackageNotFoundError:
    __version__ = "0.0.0+unknown"


def optimize(dsk, keys=None, **kwargs):
    """Optimize a dask-array collection.

    Low-level graphs are returned unchanged because this package optimizes
    through Array expressions before graph materialization.
    """
    if isinstance(dsk, Array):
        result = dsk.optimize()
        if keys is not None:
            return result.__dask_graph__()
        return result
    return dsk


newaxis = None
nan = _np.nan
inf = _np.inf
e = _np.e
pi = _np.pi
euler_gamma = _np.euler_gamma

bool = _np.bool
int8 = _np.int8
int16 = _np.int16
int32 = _np.int32
int64 = _np.int64
uint8 = _np.uint8
uint16 = _np.uint16
uint32 = _np.uint32
uint64 = _np.uint64
float32 = _np.float32
float64 = _np.float64
complex64 = _np.complex64
complex128 = _np.complex128

# xarray integration is opt-in and never happens as a side effect of importing
# this package: call dask_array.xarray.register() (see _xarray.py). Note that
# xarray imports dask_array on its own -- Dataset.__dask_exprs__ does
# import_module("dask_array") whenever it is installed -- so registering here
# would silently take over xarray for anyone who merely has us installed.

# Star-import surface: public functions, classes, and constants only.
# Submodules (io, xarray, random, ...) are deliberately excluded so that
# `from dask_array import *` never shadows the stdlib or the real xarray.
__all__ = [
    "Array",
    "PerformanceWarning",
    "abs",
    "absolute",
    "add",
    "aligned_coarsen_chunks",
    "all",
    "allclose",
    "angle",
    "any",
    "append",
    "apply_along_axis",
    "apply_gufunc",
    "apply_over_axes",
    "arange",
    "arccos",
    "arccosh",
    "arcsin",
    "arcsinh",
    "arctan",
    "arctan2",
    "arctanh",
    "arg_reduction",
    "argmax",
    "argmin",
    "argtopk",
    "argwhere",
    "around",
    "array",
    "as_gufunc",
    "asanyarray",
    "asarray",
    "atleast_1d",
    "atleast_2d",
    "atleast_3d",
    "average",
    "bincount",
    "bitwise_and",
    "bitwise_not",
    "bitwise_or",
    "bitwise_xor",
    "block",
    "blockwise",
    "bool",
    "broadcast_arrays",
    "broadcast_to",
    "cbrt",
    "ceil",
    "choose",
    "chunk_report",
    "clip",
    "coarsen",
    "complex128",
    "complex64",
    "compress",
    "compute",
    "concatenate",
    "conj",
    "conjugate",
    "copysign",
    "corrcoef",
    "cos",
    "cosh",
    "count_nonzero",
    "cov",
    "cumprod",
    "cumreduction",
    "cumsum",
    "deg2rad",
    "degrees",
    "delete",
    "diag",
    "diagonal",
    "diff",
    "digitize",
    "divide",
    "divmod",
    "dot",
    "dstack",
    "e",
    "ediff1d",
    "einsum",
    "elemwise",
    "empty",
    "empty_like",
    "equal",
    "euler_gamma",
    "exp",
    "exp2",
    "expand_dims",
    "explain",
    "expm1",
    "expr_flow",
    "expr_table",
    "extract",
    "eye",
    "fabs",
    "fix",
    "flatnonzero",
    "flip",
    "fliplr",
    "flipud",
    "float32",
    "float64",
    "float_power",
    "floor",
    "floor_divide",
    "fmax",
    "fmin",
    "fmod",
    "frexp",
    "from_array",
    "from_delayed",
    "from_map",
    "from_npy_stack",
    "from_tiledb",
    "from_zarr",
    "fromfunction",
    "frompyfunc",
    "full",
    "full_like",
    "gradient",
    "greater",
    "greater_equal",
    "gufunc",
    "histogram",
    "histogram2d",
    "histogramdd",
    "hstack",
    "hypot",
    "i0",
    "imag",
    "indices",
    "inf",
    "insert",
    "int16",
    "int32",
    "int64",
    "int8",
    "invert",
    "isclose",
    "iscomplex",
    "iscomplexobj",
    "isfinite",
    "isin",
    "isinf",
    "isnan",
    "isneginf",
    "isnull",
    "isposinf",
    "isreal",
    "ldexp",
    "left_shift",
    "less",
    "less_equal",
    "linspace",
    "log",
    "log10",
    "log1p",
    "log2",
    "logaddexp",
    "logaddexp2",
    "logical_and",
    "logical_not",
    "logical_or",
    "logical_xor",
    "map_blocks",
    "map_overlap",
    "matmul",
    "max",
    "maximum",
    "mean",
    "median",
    "meshgrid",
    "min",
    "minimum",
    "mod",
    "modf",
    "moment",
    "moveaxis",
    "multiply",
    "nan",
    "nan_to_num",
    "nanargmax",
    "nanargmin",
    "nancumprod",
    "nancumsum",
    "nanmax",
    "nanmean",
    "nanmedian",
    "nanmin",
    "nanpercentile",
    "nanprod",
    "nanquantile",
    "nanstd",
    "nansum",
    "nanvar",
    "ndim",
    "negative",
    "newaxis",
    "nextafter",
    "nonzero",
    "normalize_chunks",
    "not_equal",
    "notnull",
    "ones",
    "ones_like",
    "optimize",
    "outer",
    "overlap",
    "pad",
    "percentile",
    "pi",
    "piecewise",
    "positive",
    "power",
    "prod",
    "ptp",
    "push",
    "quantile",
    "rad2deg",
    "radians",
    "ravel",
    "ravel_multi_index",
    "real",
    "rechunk",
    "reciprocal",
    "reduction",
    "register_chunk_type",
    "remainder",
    "repeat",
    "reshape",
    "reshape_blockwise",
    "result_type",
    "right_shift",
    "rint",
    "roll",
    "rollaxis",
    "rot90",
    "round",
    "searchsorted",
    "select",
    "shape",
    "shuffle",
    "sign",
    "signbit",
    "sin",
    "sinc",
    "sinh",
    "sliding_window_view",
    "spacing",
    "sqrt",
    "square",
    "squeeze",
    "stack",
    "std",
    "store",
    "subtract",
    "sum",
    "swapaxes",
    "take",
    "tan",
    "tanh",
    "tensordot",
    "tile",
    "to_hdf5",
    "to_npy_stack",
    "to_tiledb",
    "to_zarr",
    "topk",
    "trace",
    "trace_rewrites",
    "transpose",
    "tri",
    "tril",
    "tril_indices",
    "tril_indices_from",
    "trim_overlap",
    "triu",
    "triu_indices",
    "triu_indices_from",
    "true_divide",
    "trunc",
    "ufunc",
    "uint16",
    "uint32",
    "uint64",
    "uint8",
    "unify_chunks",
    "union1d",
    "unique",
    "unravel_index",
    "var",
    "vdot",
    "vstack",
    "where",
    "zeros",
    "zeros_like",
]
