from __future__ import annotations

import dask_array._backends
from dask_array import _chunk as chunk
from dask_array._core_utils import PerformanceWarning


def _array_expr_enabled():
    """Always True for standalone dask-array package."""
    return True


from dask_array import fft, random
from dask_array._collection import (
    Array,
    array,
    asanyarray,
    asarray,
    atleast_1d,
    atleast_2d,
    atleast_3d,
    block,
    blockwise,
    broadcast_to,
    concatenate,
    dstack,
    elemwise,
    expand_dims,
    flip,
    fliplr,
    flipud,
    from_array,
    hstack,
    moveaxis,
    ravel,
    rechunk,
    reshape,
    reshape_blockwise,
    roll,
    rollaxis,
    rot90,
    squeeze,
    stack,
    swapaxes,
    transpose,
    vstack,
)
from dask_array._einsum import einsum
from dask_array._gufunc import *
from dask_array._histogram import histogram, histogram2d, histogramdd
from dask_array._map_blocks import map_blocks
from dask_array._optimize import optimize
from dask_array._overlap import map_overlap, overlap, trim_overlap
from dask_array._routines import (
    aligned_coarsen_chunks,
    allclose,
    append,
    apply_along_axis,
    apply_over_axes,
    argtopk,
    argwhere,
    around,
    average,
    bincount,
    broadcast_arrays,
    choose,
    coarsen,
    compress,
    corrcoef,
    count_nonzero,
    cov,
    delete,
    digitize,
    ediff1d,
    extract,
    flatnonzero,
    gradient,
    insert,
    isclose,
    iscomplexobj,
    isin,
    isnull,
    ndim,
    nonzero,
    notnull,
    outer,
    piecewise,
    ptp,
    ravel_multi_index,
    result_type,
    round,
    searchsorted,
    select,
    shape,
    take,
    topk,
    tril,
    tril_indices,
    tril_indices_from,
    triu,
    triu_indices,
    triu_indices_from,
    unify_chunks,
    union1d,
    unique,
    unravel_index,
)
from dask_array._shuffle import shuffle
from dask_array._ufunc import *
from dask_array.creation import (
    arange,
    diag,
    diagonal,
    empty,
    empty_like,
    eye,
    fromfunction,
    full,
    full_like,
    indices,
    linspace,
    meshgrid,
    ones,
    ones_like,
    pad,
    repeat,
    tile,
    tri,
    zeros,
    zeros_like,
)
from dask_array.io import (
    from_delayed,
    from_npy_stack,
    from_zarr,
    store,
    to_npy_stack,
    to_zarr,
)
from dask_array.linalg import dot, matmul, tensordot, vdot
from dask_array.reductions import (
    _tree_reduce,
    all,
    any,
    arg_reduction,
    argmax,
    argmin,
    cumprod,
    cumreduction,
    cumsum,
    max,
    mean,
    median,
    min,
    moment,
    nanargmax,
    nanargmin,
    nancumprod,
    nancumsum,
    nanmax,
    nanmean,
    nanmedian,
    nanmin,
    nanpercentile,
    nanprod,
    nanquantile,
    nanstd,
    nansum,
    nanvar,
    percentile,
    prod,
    quantile,
    reduction,
    std,
    sum,
    trace,
    var,
)
from dask_array.routines._diff import diff
from dask_array.routines._where import where
