from __future__ import annotations

from dask_array.reductions._arg_reduction import arg_reduction
from dask_array.reductions._common import (
    all,
    any,
    argmax,
    argmin,
    nannumel,
    nanargmax,
    nanargmin,
    max,
    mean,
    median,
    min,
    moment,
    nanmax,
    nanmean,
    nanmedian,
    nanmin,
    nanprod,
    nanquantile,
    nanstd,
    nansum,
    nanvar,
    numel,
    prod,
    quantile,
    std,
    sum,
    var,
)
from dask_array.reductions._cumulative import (
    cumprod,
    cumreduction,
    cumsum,
    nancumprod,
    nancumsum,
)
from dask_array.reductions._reduction import (
    _tree_reduce,
    reduction,
)
from dask_array.reductions._trace import trace
from dask_array.reductions._percentile import nanpercentile, percentile

__all__ = [
    "all",
    "any",
    "arg_reduction",
    "argmax",
    "argmin",
    "cumprod",
    "cumreduction",
    "cumsum",
    "max",
    "mean",
    "median",
    "min",
    "moment",
    "nanargmax",
    "nanargmin",
    "nancumprod",
    "nancumsum",
    "nanmax",
    "nanmean",
    "nanmedian",
    "nanmin",
    "nanpercentile",
    "nanprod",
    "nanquantile",
    "nanstd",
    "nansum",
    "nanvar",
    "percentile",
    "prod",
    "quantile",
    "reduction",
    "std",
    "sum",
    "trace",
    "var",
    "_tree_reduce",
]
